# run commands for analysis,

# here goes your shell script
executable    = submit_ddsim.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/condor/std-ddsim/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/condor/std-ddsim/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/condor/std-ddsim/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "workday"
arguments="0 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_0.root"
queue
arguments="700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_1.root"
queue
arguments="1400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_2.root"
queue
arguments="2100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_3.root"
queue
arguments="2800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_4.root"
queue
arguments="3500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_5.root"
queue
arguments="4200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_6.root"
queue
arguments="4900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_7.root"
queue
arguments="5600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_8.root"
queue
arguments="6300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_9.root"
queue
arguments="7000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_10.root"
queue
arguments="7700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_11.root"
queue
arguments="8400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_12.root"
queue
arguments="9100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_13.root"
queue
arguments="9800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_14.root"
queue
arguments="10500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_15.root"
queue
arguments="11200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_16.root"
queue
arguments="11900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_17.root"
queue
arguments="12600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_18.root"
queue
arguments="13300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_19.root"
queue
arguments="14000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_20.root"
queue
arguments="14700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_21.root"
queue
arguments="15400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_22.root"
queue
arguments="16100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_23.root"
queue
arguments="16800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_24.root"
queue
arguments="17500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_25.root"
queue
arguments="18200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_26.root"
queue
arguments="18900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_27.root"
queue
arguments="19600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_28.root"
queue
arguments="20300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_29.root"
queue
arguments="21000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_30.root"
queue
arguments="21700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_31.root"
queue
arguments="22400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_32.root"
queue
arguments="23100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_33.root"
queue
arguments="23800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_34.root"
queue
arguments="24500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_35.root"
queue
arguments="25200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_36.root"
queue
arguments="25900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_37.root"
queue
arguments="26600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_38.root"
queue
arguments="27300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_39.root"
queue
arguments="28000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_40.root"
queue
arguments="28700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_41.root"
queue
arguments="29400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_42.root"
queue
arguments="30100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_43.root"
queue
arguments="30800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_44.root"
queue
arguments="31500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_45.root"
queue
arguments="32200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_46.root"
queue
arguments="32900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_47.root"
queue
arguments="33600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_48.root"
queue
arguments="34300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_49.root"
queue
arguments="35000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_50.root"
queue
arguments="35700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_51.root"
queue
arguments="36400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_52.root"
queue
arguments="37100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_53.root"
queue
arguments="37800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_54.root"
queue
arguments="38500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_55.root"
queue
arguments="39200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_56.root"
queue
arguments="39900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_57.root"
queue
arguments="40600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_58.root"
queue
arguments="41300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_59.root"
queue
arguments="42000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_60.root"
queue
arguments="42700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_61.root"
queue
arguments="43400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_62.root"
queue
arguments="44100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_63.root"
queue
arguments="44800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_64.root"
queue
arguments="45500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_65.root"
queue
arguments="46200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_66.root"
queue
arguments="46900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_67.root"
queue
arguments="47600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_68.root"
queue
arguments="48300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_69.root"
queue
arguments="49000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_70.root"
queue
arguments="49700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_71.root"
queue
arguments="50400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_72.root"
queue
arguments="51100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_73.root"
queue
arguments="51800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_74.root"
queue
arguments="52500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_75.root"
queue
arguments="53200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_76.root"
queue
arguments="53900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_77.root"
queue
arguments="54600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_78.root"
queue
arguments="55300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_79.root"
queue
arguments="56000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_80.root"
queue
arguments="56700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_81.root"
queue
arguments="57400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_82.root"
queue
arguments="58100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_83.root"
queue
arguments="58800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_84.root"
queue
arguments="59500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_85.root"
queue
arguments="60200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_86.root"
queue
arguments="60900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_87.root"
queue
arguments="61600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_88.root"
queue
arguments="62300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_89.root"
queue
arguments="63000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_90.root"
queue
arguments="63700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_91.root"
queue
arguments="64400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_92.root"
queue
arguments="65100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_93.root"
queue
arguments="65800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_94.root"
queue
arguments="66500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_95.root"
queue
arguments="67200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_96.root"
queue
arguments="67900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_97.root"
queue
arguments="68600 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_98.root"
queue
arguments="69300 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_99.root"
queue
arguments="70000 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_100.root"
queue
arguments="70700 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_101.root"
queue
arguments="71400 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_102.root"
queue
arguments="72100 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_103.root"
queue
arguments="72800 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_104.root"
queue
arguments="73500 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_105.root"
queue
arguments="74200 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_106.root"
queue
arguments="74900 700 /eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_107.root"
queue
