# run commands for analysis,

# here goes your shell script
executable    = submit_ddsim.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "espresso"
arguments="/afs/cern.ch/work/s/saaumill/public/tmp_fullsim_output/ddsim_higgsgamma/ddsim_higgsgamma_0.root /afs/cern.ch/work/s/saaumill/public/tmp_fullsim_output/reco_higgsgamma/reco_higgsgamma_0.root"
queue