# run commands for analysis,

# here goes your shell script
executable    = submit_reco_withJetTagger.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/condor/std-reco/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "workday"
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_0.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_0.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_1.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_1.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_10.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_2.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_100.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_3.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_101.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_4.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_102.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_5.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_103.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_6.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_104.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_7.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_105.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_8.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_106.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_9.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_107.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_10.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_11.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_11.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_12.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_12.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_13.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_13.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_14.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_14.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_15.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_15.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_16.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_16.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_17.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_17.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_18.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_18.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_19.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_19.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_2.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_20.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_20.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_21.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_21.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_22.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_22.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_23.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_23.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_24.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_24.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_25.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_25.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_26.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_26.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_27.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_27.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_28.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_28.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_29.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_29.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_30.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_3.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_31.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_30.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_32.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_31.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_33.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_32.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_34.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_33.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_35.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_34.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_36.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_35.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_37.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_36.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_38.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_37.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_39.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_38.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_40.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_39.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_41.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_4.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_42.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_40.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_43.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_41.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_44.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_42.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_45.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_43.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_46.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_44.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_47.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_45.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_48.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_46.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_49.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_47.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_50.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_48.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_51.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_49.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_52.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_5.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_53.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_50.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_54.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_51.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_55.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_52.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_56.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_53.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_57.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_54.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_58.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_55.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_59.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_56.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_60.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_57.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_61.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_58.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_62.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_59.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_63.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_6.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_64.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_60.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_65.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_61.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_66.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_62.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_67.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_63.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_68.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_64.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_69.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_65.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_70.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_66.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_71.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_67.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_72.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_68.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_73.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_69.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_74.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_7.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_75.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_70.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_76.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_71.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_77.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_72.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_78.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_73.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_79.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_74.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_80.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_75.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_81.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_76.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_82.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_77.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_83.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_78.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_84.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_79.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_85.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_8.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_86.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_80.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_87.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_81.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_88.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_82.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_89.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_83.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_90.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_84.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_91.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_85.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_92.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_86.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_93.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_87.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_94.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_88.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_95.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_89.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_96.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_9.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_97.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_90.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_98.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_91.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_99.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_92.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_100.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_93.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_101.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_94.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_102.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_95.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_103.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_96.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_104.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_97.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_105.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_98.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_106.root"
queue
arguments="/eos/user/s/saaumill/Hgamma_fullsim_data/ddsim_higgsgamma/ddsim_higgsgamma_99.root /eos/user/s/saaumill/Hgamma_fullsim_data/reco_higgsgamma/reco_higgsgamma_107.root"
queue
